### ISSUE TITLE
ffmpeg4

### ISSUE THREAD

**Issue by loretoparisi** [alexellis/node-streaming-template#1]
Hello, thanks for this amazing example!
This example will use `ffmpeg3` because by defaults `ffmpeg4` is not available on pip. I have tried this solution that will work in debian:

```bash
sudo apt-get update
sudo apt-get install deb-multimedia-keyring
sudo apt-get update
sudo apt-get install ffmpeg
```

but it does not work in this case.

**Comment by alexellis** [comment]
Hi @loretoparisi 

There is no need to install ffmpeg via apt-get, both of these templates use Alpine Linux, not Debian.

Clone this repository, then run: `faas-cli build -f ffmpeg.yml`

Alex
